INTERNAL_NETWORK: 192.168.56.0/24
NETWORK_GATEWAY: 192.168.56.1
DOMAIN_NAME: cluster.ma
MASTER: 192.168.56.10 # master ip for now [change it after load balancing]

# default
ansible_os_family: RedHat
